ads/urls.py
from django.conf import settings
from django.conf.urls import url, patterns, include
from django.contrib import admin
from django.conf.urls.static import static


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url('', include('core.urls', namespace="core")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#if settings.DEBUG:
    #import debug_toolbar
    #urlpatterns += patterns('',
    #    url(r'^__debug__/', include(debug_toolbar.urls)),
    #)

app/core/urls.py
from django.conf.urls import patterns, url
from core.views import *

urlpatterns = patterns('',
                       url(r'^$', HomePageView.as_view(), name='core__homepage'),
                       url(r'^(?P<pk>[-\w]+)/$', AdsDetailView.as_view(), name='core__ads_detail'),
                       )

app/core/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class BaseModel(models.Model):
    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

"""
#
# AdsModel(info)
#
"""


class AdsModel(BaseModel):
    name = models.CharField("Name", max_length=500, blank=True, null=True)
    description = models.TextField('Description', blank=True, null=True)

app/core/views.py
# -*- coding: utf-8 -*-
import datetime

import jwt
import redis
from django.conf import settings
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView
from hitcount.views import HitCountDetailView

from core.models import AdsModel

r = redis.StrictRedis(host='localhost', port=6379, db=0)

"""
#
# HomePageView
#
"""


class HomePageView(ListView):
    template_name = 'core/list.html'
    model = AdsModel
    ordering = ['-created']


"""
#
# AdsDetailView
#
"""
def create_key(user, obj, session_key, ip):
    payload = {
        'user_id': user.id,
        'obj_id': obj.id,
        'session_key': session_key,
        'ip': ip
    }
    key = jwt.encode(payload, settings.SECRET_KEY)
    k = "sorter_" + str(obj.id) + "_" + key.decode('unicode_escape')
    return k

def parse_key(key, obj):
    key = key.replace('sorter_' + str(obj.id) + '_', '')
    return jwt.decode(key, settings.SECRET_KEY)

"""
#
# Можем проверять по всем данным, запустить celery что очищал редис и забивал в базу и т.п. Дорабывать есть куда
#
"""

class AdsDetailView(HitCountDetailView):
    template_name = 'core/detail.html'
    model = AdsModel
    count_hit = True
    counter_views = {}

    def counter(self, *args, **kwargs):

        # формируем значения ключа для редис
        session_key = self.request.session.session_key
        ip = self.request.META['REMOTE_ADDR']
        obj = self.get_object()

        viewed = True

        # создаем ключ
        key = create_key(self.request.user, obj, session_key, ip)

        # если нету записываем в редис
        if not r.get(key):
            viewed = False
            r.set(key, str(obj.id))

        parser_key = parse_key(key, obj)

        print(key)
        print(parser_key)

        self.counter_views['counter'] = len(r.keys('sorter_1_*'))
        self.counter_views['viewed'] = viewed


    def dispatch(self, *args, **kwargs):

        self.counter(*args, **kwargs)

        return super(AdsDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AdsDetailView, self).get_context_data(**kwargs)

        context['counter_views'] = self.counter_views
        return context

templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block content %}

{% endblock %}

templates/core/detail.html
{% extends 'base.html' %}

{% block content %}



<h1 class="text-center">{{ object.name }}</h1>

<ul class="list-group">
  <li class="list-group-item">
  <p>{{ object.description }}</p>
    {% if counter_views.viewed %}<br>
    <b>Вы уже смотрели это объявление</b>
    {% endif %}
    <br>
    <b>Просмотров:{{ counter_views.counter }}</b>
  </li>
</ul>

{% endblock %}

templates/core/list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-center">Ads</h1>

<ul class="list-group">
    {% for ads in object_list %}
  <li class="list-group-item">
  <h1>{{ ads.created|date }} - <a href="{% url "core:core__ads_detail" ads.id %}">{{ ads.name }}</a></h1>
  <p>{{ ads.description }}</p>
  </li>
    {% empty %}
     <li class="list-group-item">No ads yet.</li>
    {% endfor %}
</ul>

{% endblock %}